defaults: &defaults
  dump_command:    pg_dump -U {{user}} -w {{compress}} -b -a -h {{hostname}} -t {{tablename}} {{databasename}} -f {{output_directory}}/{{filename}}
  archive_folder:  /home/ntb/Public/rails_archive/public/system/shapefiles

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults