development:
  adapter:  postgis
  encoding: unicode
  host:     localhost
  port:     5432
  database: finspweb_dev
  username: postgres
  password: password
  pool: 20

test:
  adapter:  postgis
  encoding: unicode
  host:     localhost
  port:     5432
  database: finspweb_dev
  username: postgres
  password: password
  pool: 20

production:
  adapter: postgis
  encoding: unicode
  host:     localhost
  port:     5432
  database: finspweb_dev
  username: postgres
  password: password
  pool: 20
