development:
  adapter:  postgis
  encoding: unicode
  host:     localhost
  port:     5432
  database: inspire
  username: inspire
  pool: 20

test:
  adapter:  postgis
  encoding: unicode
  host:     localhost
  port:     5432
  database: inspire
  username: inspire
  pool: 20

production:
  adapter: postgis
  encoding: unicode
  host:     localhost
  port:     5432
  database: inspire
  username: inspire
  pool: 20
